title: GitHub pages tutorial
author: alu0101328447
email: alu010132847@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
